basePath: /api
info:
  contact:
    email: alexander.klonov@mail.ru
  description: Test Task for building api for todolist
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: ToDoList api
  version: "1.0"
paths: {}
swagger: "2.0"
